#!/usr/bin/env python3
"""Package generated fox skill strips: chroma extraction, shared scale, fixed feet, atlas and GIF QA.

Run with the project's Python environment containing Pillow and NumPy.
Input provenance, frame cuts and generator prompts live beside the raw masters.
This performs deterministic asset packaging; character poses and effects are generated by imagegen.
"""
import json
import sys
from pathlib import Path
import numpy as np
from PIL import Image
from repack_generated_sprite_strip import find_components, crop_component

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / 'ArtSource/Raw/Characters/Bosses/FoxDemon/Skills_20260906'
PREVIEW = ROOT / 'ArtSource/Previews/Characters/Bosses/FoxDemon/Skills_20260906'
CHAR = ROOT / 'Assets/Art/Generated/Characters/Bosses/FoxDemon'
VFX = ROOT / 'Assets/Art/Generated/Effects/FoxDemon'


def key_character(path):
    data = np.array(Image.open(path).convert('RGBA'))
    rgb = data[:, :, :3].astype(float)
    excess = rgb[:, :, 1] - np.maximum(rgb[:, :, 0], rgb[:, :, 2])
    key = (excess > 35) & (rgb[:, :, 1] > 130)
    data[key, 3] = 0
    # Chroma spill only at green-dominant fringe pixels; white fur and muted jade remain intact.
    spill = (excess > 20) & (rgb[:, :, 1] > 130)
    data[spill, 1] = np.maximum(data[spill, 0], data[spill, 2])
    return Image.fromarray(data)


def preview(frames, name, fps):
    PREVIEW.mkdir(parents=True, exist_ok=True)
    # Dark matte GIF avoids GIF's one-bit alpha fringes; production PNG retains true alpha.
    images=[]
    for frame in frames:
        image=Image.new('RGBA',(256,256),(24,28,30,255));image.alpha_composite(frame)
        images.append(image.convert('RGB'))
    images[0].save(PREVIEW/(name+'.gif'),save_all=True,append_images=images[1:],duration=round(1000/fps),loop=0)
    board=Image.new('RGBA',(256*len(frames),256),(24,28,30,255))
    for i,frame in enumerate(frames): board.alpha_composite(frame,(256*i,0))
    board.convert('RGB').save(PREVIEW/(name+'_contact.png'))
    images[len(images)//2].resize((1024,1024),Image.Resampling.NEAREST).save(PREVIEW/(name+'_4x.png'))


def main():
    config=json.loads((RAW/'sources.json').read_text())
    records=[]
    visual_scales={}
    character_crops={}
    for skill,entry in config['characters'].items():
        source=key_character(ROOT/entry['path'])
        components=sorted(find_components(source,24,500),key=lambda c:c[1][0])
        if len(components) != 8:
            raise ValueError(f'{skill}: expected 8 separate full-body components, got {len(components)}')
        character_crops[skill]=[crop_component(source,bounds,pixels) for _,bounds,pixels in components]
    # One scale for each entire strip, never scale frames independently. Match standing height to existing idle.
    seed=Image.open(CHAR/'spr_boss_fox_demon_idle_right_8f_v01.png').convert('RGBA').crop((0,0,256,256))
    # Existing approved atlas toes are at x=147.5, y=223; retain this visible foot offset
    # while keeping the project Sprite pivot (128,32), so the older idle/attack clips do not jump.
    foot_x=147.5
    for skill,crops in character_crops.items():
        anchors=[]
        for crop in crops:
            alpha=np.array(crop.getchannel('A'))
            ys,xs=np.where(alpha[max(0,crop.height-10):]>24)
            anchors.append((float(xs.min()+xs.max())/2 if len(xs) else crop.width/2,crop.height))
        left=max(a[0] for a in anchors)
        right=max(c.width-a[0] for c,a in zip(crops,anchors))
        scale=min(214/max(c.height for c in crops), (foot_x-8)/max(1,left), (248-foot_x)/max(1,right))
        frames=[]
        for crop,anchor in zip(crops,anchors):
            resized=crop.resize((max(1,round(crop.width*scale)),max(1,round(crop.height*scale))),Image.Resampling.NEAREST)
            slot=Image.new('RGBA',(256,256))
            offset=(round(foot_x-anchor[0]*scale),224-resized.height)
            if offset[0]<0 or offset[0]+resized.width>256 or offset[1]<0: raise ValueError('Out-of-slot character')
            slot.alpha_composite(resized,offset);frames.append(slot)
        # Scale the known ready pose into this strip's body scale; renderer compensates once per clip.
        seed_ratio=crops[0].height*scale/213.0
        ready=seed.resize((round(256*seed_ratio),round(256*seed_ratio)),Image.Resampling.NEAREST)
        seed_slot=Image.new('RGBA',(256,256))
        seed_slot.alpha_composite(ready,(round(foot_x*(1-seed_ratio)),round(224*(1-seed_ratio))))
        frames[0]=seed_slot.copy();frames[-1]=seed_slot.copy()
        visual_scales[skill]=1/seed_ratio
        strip=Image.new('RGBA',(2048,256))
        for i,frame in enumerate(frames):strip.alpha_composite(frame,(i*256,0))
        path=CHAR/f'spr_boss_fox_demon_{skill}_right_8f_v01.png';strip.save(path)
        preview(frames,skill,12);preview(frames,skill+'_8fps',8)
        records.append({'skill':skill,'kind':'character','path':str(path.relative_to(ROOT)),'frames':8,'size':[2048,256],
            'shared_scale':scale,'visual_scale':1/seed_ratio,'bounds':[f.getbbox() for f in frames],'status':'Normalized','first_last':'existing in-engine idle seed'})
    for skill,entry in config['effects'].items():
        source=Image.open(ROOT/entry['path']).convert('RGBA')
        if source.getchannel('A').getextrema()[0] != 0: raise ValueError('VFX master lacks transparency')
        cuts=entry['cuts'];frames=[];bounds=[]
        for a,b in zip(cuts,cuts[1:]):
            f=source.crop((a,0,b,source.height));box=f.getbbox()
            if not box:raise ValueError('Empty effect')
            frames.append(f.crop(box));bounds.append(box)
        scale=224/max(max(f.size) for f in frames)
        slots=[]
        for f in frames:
            f=f.resize((max(1,round(f.width*scale)),max(1,round(f.height*scale))),Image.Resampling.NEAREST)
            slot=Image.new('RGBA',(256,256));slot.alpha_composite(f,((256-f.width)//2,(256-f.height)//2));slots.append(slot)
        VFX.mkdir(parents=True,exist_ok=True)
        strip=Image.new('RGBA',(1536,256))
        for i,slot in enumerate(slots):strip.alpha_composite(slot,(i*256,0))
        path=VFX/f'spr_vfx_fox_{skill}_6f_v01.png';strip.save(path)
        preview(slots,'vfx_'+skill,12)
        records.append({'skill':skill,'kind':'effect','path':str(path.relative_to(ROOT)),'frames':6,'size':[1536,256],
            'shared_scale':scale,'source_cuts':cuts,'status':'Normalized'})
    (PREVIEW/'visual_scales.json').write_text(json.dumps(visual_scales,indent=2))
    (PREVIEW/'normalization.json').write_text(json.dumps(records,indent=2))
    print(json.dumps(records,indent=2))

if __name__=='__main__': main()
