// Deterministic packing only; poses are generated by the built-in image tool.
// Requires sharp. Run from the repository root with NODE_PATH pointing to sharp.
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');
const root = path.resolve(__dirname, '../..');
const source = path.join(root, 'ArtSource/HeroEightDirections');
const dest = path.join(root, 'Assets/Resources/Characters/HeroEightDirections');
const review = path.join(root, 'docs/validation/hero_eight_directions');
const directions = ['down', 'down_right', 'right', 'up_right', 'up', 'up_left', 'left', 'down_left'];
const median = a => a.sort((a,b)=>a-b)[Math.floor(a.length/2)];

// Remove only bright neutral background connected to the cell boundary.
// White clothing enclosed by the dark outline remains opaque.
async function cut(image, rect) {
  const {data, info} = await sharp(image).extract(rect).removeAlpha().raw().toBuffer({resolveWithObject:true});
  const w=info.width, h=info.height, count=w*h, seen=new Uint8Array(count), queue=new Int32Array(count);
  let head=0, tail=0;
  function visit(i) {
    if(seen[i]) return;
    const p=i*3, lo=Math.min(data[p],data[p+1],data[p+2]), hi=Math.max(data[p],data[p+1],data[p+2]);
    if(lo>=190 && hi-lo<=27) { seen[i]=1; queue[tail++]=i; }
  }
  for(let x=0;x<w;x++){ visit(x); visit((h-1)*w+x); }
  for(let y=0;y<h;y++){ visit(y*w); visit(y*w+w-1); }
  while(head<tail){const i=queue[head++],x=i%w,y=Math.floor(i/w); if(x)visit(i-1);if(x<w-1)visit(i+1);if(y)visit(i-w);if(y<h-1)visit(i+w);}
  // Keep the principal connected silhouette, removing isolated background specks.
  const labels=new Int32Array(count); let best=0,bestSize=0,label=0;
  for(let i=0;i<count;i++) if(!seen[i]&&!labels[i]) {
    label++;head=0;tail=1;queue[0]=i;labels[i]=label;
    while(head<tail){ const p=queue[head++],x=p%w,y=Math.floor(p/w);
      for(const n of [x?p-1:-1,x<w-1?p+1:-1,y?p-w:-1,y<h-1?p+w:-1])
        if(n>=0&&!seen[n]&&!labels[n]){labels[n]=label;queue[tail++]=n;}
    }
    if(tail>bestSize){bestSize=tail;best=label;}
  }
  let x0=w,y0=h,x1=0,y1=0; const rgba=Buffer.alloc(count*4);
  for(let i=0;i<count;i++) if(labels[i]===best){
    const x=i%w,y=Math.floor(i/w);x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);
    rgba[i*4]=data[i*3];rgba[i*4+1]=data[i*3+1];rgba[i*4+2]=data[i*3+2];rgba[i*4+3]=255;
  }
  if(x0===0||x1===w-1||y0===0||y1===h-1||bestSize<1000) throw Error('Clipped or empty sprite '+JSON.stringify({image,rect,box:[x0,y0,x1,y1],bestSize}));
  // Waist center is more stable than hair/stride silhouette center.
  const centers=[];
  for(let y=Math.round(y0+(y1-y0)*.50);y<=Math.round(y0+(y1-y0)*.65);y++){
    const xs=[];for(let x=x0;x<=x1;x++)if(rgba[(y*w+x)*4+3])xs.push(x);
    if(xs.length)centers.push(median(xs));
  }
  const anchorX=median(centers);
  // Enclosed checkerboard islands inside ponytail loops are also background.
  // Restrict this to the upper silhouette outside the head/torso center;
  // the white lapels, cuffs, boot bands and tiny eye glints stay intact.
  const checked=new Uint8Array(count);
  function pale(i){const p=i*4;return rgba[p+3]&&Math.min(rgba[p],rgba[p+1],rgba[p+2])>=210&&Math.max(rgba[p],rgba[p+1],rgba[p+2])-Math.min(rgba[p],rgba[p+1],rgba[p+2])<20;}
  for(let i=0;i<count;i++)if(!checked[i]&&pale(i)){
    head=0;tail=1;queue[0]=i;checked[i]=1;let sx=0,sy=0;
    while(head<tail){const p=queue[head++],x=p%w,y=Math.floor(p/w);sx+=x;sy+=y;
      for(const n of [x?p-1:-1,x<w-1?p+1:-1,y?p-w:-1,y<h-1?p+w:-1])if(n>=0&&!checked[n]&&pale(n)){checked[n]=1;queue[tail++]=n;}
    }
    if(tail>18&&sy/tail<y0+(y1-y0)*.48&&Math.abs(sx/tail-anchorX)>(y1-y0)*.08)
      for(let n=0;n<tail;n++)rgba[queue[n]*4+3]=0;
  }
  return {rgba,w,h,box:{left:x0,top:y0,width:x1-x0+1,height:y1-y0+1},anchorX};
}
async function pack(c, scale){
  const width=Math.round(c.box.width*scale),height=Math.round(c.box.height*scale);
  const left=Math.round(128-(c.anchorX-c.box.left)*scale);
  let top=224-height;
  if(left<8||left+width>248||top<8) throw Error('Insufficient frame padding');
  const input=await sharp(c.rgba,{raw:{width:c.w,height:c.h,channels:4}}).extract(c.box).resize(width,height,{kernel:'nearest'}).png().toBuffer();
  const pixels=await sharp(input).raw().toBuffer();let lastY=height-1;
  while(lastY>0&&!pixels.subarray(lastY*width*4,(lastY+1)*width*4).some((v,i)=>i%4===3&&v>0))lastY--;
  top=223-lastY; // Nearest-neighbor sampling can omit a one-pixel sole tip.
  return sharp({create:{width:256,height:256,channels:4,background:'#00000000'}}).composite([{input,left,top}]).png().toBuffer();
}
(async()=>{
  fs.mkdirSync(dest,{recursive:true});fs.mkdirSync(review,{recursive:true});
  const manifest={frameSize:256,framesPerDirection:8,fps:12,ppu:160,pivot:[.5,.125],footPixelY:224,directions:[]};
  const ref=path.join(source,'reference.jpeg'), refMeta=await sharp(ref).metadata();
  const idleCuts=[];
  for(let d=0;d<8;d++)idleCuts.push(await cut(ref,{left:Math.round(d%4*refMeta.width/4),top:d<4?0:530,width:refMeta.width/4,height:d<4?530:refMeta.height-530}));
  const sheet=[], idleSheet=[], cycles=Array.from({length:8},()=>[]);
  for(let d=0;d<8;d++){
    const direction=directions[d],raw=path.join(source,'raw',direction+'.png'),meta=await sharp(raw).metadata(),cuts=[];
    const pixels=await sharp(raw).removeAlpha().raw().toBuffer(), bands=[];
    let start=-1;
    for(let x=0;x<=meta.width;x++){
      let dark=0; if(x<meta.width)for(let y=0;y<meta.height;y++){const i=(y*meta.width+x)*3;if(Math.min(pixels[i],pixels[i+1],pixels[i+2])<170)dark++;}
      if(dark>3&&start<0)start=x;
      if(dark<=3&&start>=0){if(x-start>20)bands.push([start,x]);start=-1;}
    }
    if(bands.length!==8)throw Error(direction+' expected 8 silhouettes: '+JSON.stringify(bands));
    for(let f=0;f<8;f++){
      const left=f===0?0:Math.round((bands[f-1][1]+bands[f][0])/2),right=f===7?meta.width:Math.round((bands[f][1]+bands[f+1][0])/2);
      cuts.push(await cut(raw,{left,top:0,width:right-left,height:meta.height}));
    }
    const scale=192/median(cuts.map(c=>c.box.height)),frames=[];
    for(let f=0;f<8;f++){
      const input=await pack(cuts[f],scale);frames.push({input,left:f*256,top:0});
      sheet.push({input,left:f*256,top:d*256});cycles[f].push({input,left:(d%4)*256,top:Math.floor(d/4)*256});
    }
    await sharp({create:{width:2048,height:256,channels:4,background:'#00000000'}}).composite(frames).png().toFile(path.join(dest,'spr_hero_run_'+direction+'_8f_v01.png'));
    const idleScale=192/idleCuts[d].box.height;
    const idle=await pack(idleCuts[d],idleScale);
    idleSheet.push({input:idle,left:d*256,top:0});
    fs.writeFileSync(path.join(dest,'spr_hero_idle_'+direction+'_1f_v01.png'),idle);
    manifest.directions.push({direction,scale,sourceHeights:cuts.map(c=>c.box.height),idleScale});
  }
  await sharp({create:{width:2048,height:2048,channels:4,background:'#202e32'}}).composite(sheet).png().toFile(path.join(review,'contact_sheet.png'));
  await sharp({create:{width:2048,height:256,channels:4,background:'#202e32'}}).composite(idleSheet).png().toFile(path.join(review,'idle_sheet.png'));
  for(let f=0;f<8;f++)await sharp({create:{width:1024,height:512,channels:4,background:'#202e32'}}).composite(cycles[f]).png().toFile(path.join(review,'cycle_'+f+'.png'));
  const gifFrames=[];
  for(let f=0;f<8;f++)gifFrames.push(await sharp(path.join(review,'cycle_'+f+'.png')).ensureAlpha().raw().toBuffer());
  await sharp(Buffer.concat(gifFrames),{raw:{width:1024,height:4096,channels:4,pageHeight:512}}).gif({loop:0,delay:83}).toFile(path.join(review,'movement_preview.gif'));
  fs.writeFileSync(path.join(source,'normalization.json'),JSON.stringify(manifest,null,2)+'\n');
  console.log(JSON.stringify(manifest,null,2));
})();
